# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'ReactiveCocoaDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveCocoaDemo

  pod 'ReactiveCocoa', '~> 4.2.1'

end
